"""
Django settings for comdirect project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dotenv
import dj_database_url

dotenv.load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-q+)rh&425aq#(5#2l+7_(dpu&jwj6i&q2kfe_*!v!(o4t+#m3u')

# ----------------------------------------------------------------------
# AJUSTE PARA HEROKU: Segurança e Debug
# ----------------------------------------------------------------------
# DEBUG deve ser False em produção (Heroku)
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'

# Domínios permitidos para acessar sua aplicação.
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')
if 'DYNO' in os.environ:
    # No Heroku, é mais seguro permitir todos os hosts dinâmicos
    ALLOWED_HOSTS = ['*']
# ----------------------------------------------------------------------

# Aplicações adicionadas
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Suas aplicações
    'comdirect', # O nome da sua aplicação que contém os modelos e views

    # APPS DE TERCEIROS: Apenas WhiteNoise
    # Cloudinary e cloudinary_storage removidos conforme solicitação.
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise deve vir logo após SecurityMiddleware
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Altere para o nome da sua pasta de projeto principal, 'core'
ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Adicionado para templates globais
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.messages',
            ],
        },
    },
]

# Altere para o nome da sua pasta de projeto principal, 'core'
WSGI_APPLICATION = 'core.wsgi.application'

# ----------------------------------------------------------------------
# AJUSTE PARA HEROKU: Base de Dados
# ----------------------------------------------------------------------
# Configuração padrão (para desenvolvimento local)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Se a variável de ambiente DATABASE_URL existir (no Heroku), use PostgreSQL
if os.getenv('DATABASE_URL'):
    DATABASES['default'] = dj_database_url.config(
        default=os.getenv('DATABASE_URL'),
        conn_max_age=600,
        ssl_require=True
    )
# ----------------------------------------------------------------------

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'Africa/Luanda'
USE_I18N = True
USE_TZ = True


# ----------------------------------------------------------------------
# AJUSTE PARA HEROKU: Ficheiros Estáticos (Static Files) e Mídia (Media Files)
# ----------------------------------------------------------------------
STATIC_URL = '/static/'
# O diretório onde o WhiteNoise/Django irá coletar todos os arquivos estáticos
STATIC_ROOT = BASE_DIR / 'staticfiles' 
# Diretórios adicionais onde o Django procura arquivos estáticos
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Configuração de armazenamento de arquivos
# Use WhiteNoise para arquivos estáticos em produção (CSS, JS, etc.)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Configuração de Mídia (Uploads de Utilizador):
# ATENÇÃO: Os arquivos de mídia serão salvos no sistema de arquivos temporário do Heroku e serão perdidos após o restart/deploy.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# DEFAULT_FILE_STORAGE é deixado no padrão (django.core.files.storage.FileSystemStorage)
# ----------------------------------------------------------------------

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Modelos de Autenticação
AUTH_USER_MODEL = 'comdirect.Usuario'

# URL para onde o Django redireciona para o login
LOGIN_URL = 'login'

# ----------------------------------------------------------------------
# AJUSTE PARA HEROKU: Segurança e Headers
# ----------------------------------------------------------------------
# Para segurança CSRF em produção
CSRF_TRUSTED_ORIGINS = ['https://*.herokuapp.com']

# Configuração obrigatória para que o Heroku possa lidar com o HTTPS/SSL
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# ----------------------------------------------------------------------
```
eof

## Passo 10: Deploy Final para a Nova Aplicação

Agora, vamos executar os comandos de deploy, garantindo que usamos o nome da aplicação e o remote corretos.

### 1. Commit Final

Se tiver havido alguma alteração local que ainda não foi comitada, faça o commit agora:

```bash
git add core/settings.py
git commit -m "Configurações de deploy final e novo app Heroku"
```

### 2. Configuração da Chave Secreta na Nova Aplicação

Copie e cole este comando para definir a chave secreta na sua **nova** aplicação (`comdirect-app-nova`):

```bash
heroku config:set DJANGO_SECRET_KEY='s$o3!Qf8pX7wZk9bLg1yM2eV4rJ5tHa6uI0eC7dNvB3mYqP8oRz' --app comdirect-app-nova
```

### 3. Deploy para o Novo Remote (`nova-heroku`)

Agora, envie o código para a nova aplicação usando o remote `nova-heroku`:

```bash
git push nova-heroku main
